---
title: El extraño del perro galgo
layout: post
author: Raúl Vieytes
image: /assets/img/cuadro-1.jpeg
---
**El extraño del perro galgo**

Dos personas cantan a dúo sin pretensiones de hacerlo frente a un público. Tienen más oportunidades de ver que de ser vistas. El público no precisa lo que ya tiene, es el inaccesible lado externo del límite. Las voces se vuelven pura comparsa de lo que entra por los ojos. Si son dos mujeres, dos varones, o se trata de una formación mixta, no importa. Y si, aunque no sea más que uno, toca un instrumento al tiempo que canta, será suficiente.  

Hay teatros y teatros. Se puede dar que, cuando toques a solas con amigos, cierres los ojos y hagas música sintiendo que es para un público. Que por dentro de la cúpula craneal tengas un teatro imaginario, que el mundo no sea otra cosa, en definitiva. Pero por algo la música comparte tantas categorías con la gráfica. Forma, intervalo, altura (bajo/alto), figura, fondo, distancia, base, motivo, cromatismo, equilibrio, línea, punto, contrapunto, marcación, brillo, claridad, tono, contraste, limpieza, modulación, ritmo, textura, gesto, valor, densidad, peso, cuerpo, volumen, formato, dimensión, curva, simetría, hay más. Partituras enteras diseñadas con patrones geométricos. Incluso en la tendencia radicalizada de aquel compositor que hablaba de vastos grupos de eventos sonoros, nubes y galaxias gobernadas por nuevas características como densidad, grado de orden, nivel de cambio, las cuales requieren definiciones y realizaciones usando la teoría de probabilidad \-es más que evidente- a la música hay que verla. Y a la pintura y la escultura \-se deduce- hay que escucharlas.  

El sonido. ¿Lo escuchas? Hay novelistas que escriben sobre melodías y armonías en una novela o un cuento y lo hacen de tal manera que, al leer, tú escuchas la música. Los personajes comentan cierto tema musical, tan conocido, interpretado en tal y tal lugar, y tú pasas a conocerlo con ellos, aunque la obra musical de la que hablan no exista fuera del mundo escrito, el mundo del silencio. Hubo quien pidió consejo a un filósofo estudioso de la música atonal para describir la obra que había compuesto su personaje de ficción: el compositor que se consideraba a sí mismo como el referente por excelencia de la música atonal, se ofendió, porque no se lo habían pedido a él. Los egos, bueno, da igual. Misma extrañeza con las voces de los personajes, sin oírlas, podría asegurar que una las escucha. ¿Escuchás tú la música que está sonando ahora, en este texto que yo escribí y tú lees? ¿Es una armonía disonante, eso? ¿O asonante? ¿O antisonante? Oír, del sonido, solamente el silencio.   

¿Y el espacio? ¿Ves el espacio del que te hablo? El espacio puede ser cualquier cosa, qué decir. Míralo: un cubo vacío, o un prisma de vidrio, de cristales de miel o de acrílico transparente, redondo, gris, suave, más liviano que el aire, para que vuele, más precisamente un prisma regular de base dodecagonal, dibujado con líneas melódicas, bien ventilado, respirable, dentro del que se ubica la gente cantando y tocando instrumentos \-hay gente aquí dentro, según está escrito- y tú puedes ver a esa gente desde todos los ángulos, la complejidad fantástica de los datos oculares, inclusive desde abajo. (Pero no es un sueño: los sueños son perfectamente esféricos. Y tú estás tanto dentro como fuera de la esfera). O puedes orbitar, como un electrón alrededor del núcleo del átomo, un átomo con un solo electrón, el electrón eres tú, que desarrollas revoluciones con la mirada fija en los músicos nucleares, un núcleo relativamente pesado, quizá pesadísimo, que te aburre, te duerme, apto para fisionarse y desencadenar una reacción en cadena. Correcto, se desencadena una cadena de desencadenamientos.  

Sigamos por los otros sentidos. El olor de la música, olfatearla. ¿Sientes el olor? Hay un olor \-te invito a contemplar cómo flota- que remite a las herramientas, algo de fierros chocando entre sí, rozándose, engranando. A quienes la ejecutan les da placer, a veces, pero también dolor, la repetición del ejercicio. Es como peinarse, a veces te da placer. Siempre hay una herramienta que es tu favorita. Quiero decir: tienes varias herramientas de la misma clase, que hacen el mismo trabajo, pero tú eliges una en particular. Es que, de tanto usarla con preferencia, ya se adaptó a ti, tu fuerza la moldeó a su propia forma. Los instrumentos musicales, en definitiva, ¿no son herramientas, como las de los escultores, o útiles, como los de los dibujantes? Pero los músicos los llaman instrumentos, prefieren no llamar herramientas a los artefactos que emplean para producir sonidos, quién sabe por qué (si le llaman “obras” a las músicas y, de sí mismos, cuando consiguen cobrar dinero, dicen que son “profesionales” y de músicos “trabajan”). Buscarás en internet etimologías, artículos, monografías que aclaren la diferencia entre herramienta e instrumento. El set de instrumentos de un músico, ¿sería apropiado llamarlo su “instrumental”? Como el instrumental de un dentista, o de un cirujano. El olor de esta música es a aceite de motor semisintético y grasa para rodamientos elaborada a base de litio.

El nivel del audio puede estar bajísimo, se puede aproximar el audio a lo inaudible, pero afilando la oreja también es factible hacer la experiencia de lo inmenso. ¡Escucha\! A propósito de esto, ahora cantan \-cada sílaba una negra (no una corchea, mucho menos una fusa), todas en la misma nota de la misma escala- una frase, un fragmento de algo clásico, en inglés (la gente sabe inglés, o simula saber, memoriza las frases y las repite sin entender qué quieren decir, hasta que aprende, no toda la gente, alguna): 

*By stating and squaring*   
*everything by reason,*   
*and by making the most rational*   
*judgement of things,*   
*every man may be*   
*in time master*  
*of every mechanic art*.

 Y el ensamble del que hablamos la contrapuntea en canon de segunda, luego las personas, unas y otras, la repiten con insistencia, se suman un número importante de voces al unísono con la primera, otro tanto al unísono con la réplica. Se distorsiona la onda con un efecto del programa de edición, el resultado es de naturaleza industrial. Y también animal. *Animal industrial*. A ver: en vez de darlas abiertas, se propone ofrecer la llave del candado que abre las palabras. Esto de las palabras cerradas como una nuez, anda también por el mismo libro que habíamos leído antes, eso diría... ¿También hay llaves y cerraduras? Mismo autor, seguro. También hubo un rey antiguo, famoso, que entró al paraíso de la especulación mística y dijo: “He bajado al jardín de las nueces”. Una caparazón dura que solo las personas fuertes y sabias sean capaces de romper, para alcanzar así la médula. Pero, entonces, ¿qué pasaría si, en vez de una sola abertura con llave, las palabras tuvieran más puertas, ventanas, claraboyas (alguien dijo setenta, alguien dijo seiscientas mil)? Incluso podrían diferenciarse entre sí, no solo en la cantidad de aberturas que perforan a cada una sino en su disposición: repartidas en forma diversa por la superficie, de manera irregular o no, más de este lado, menos del otro. O en profundidad, abriendo un pozo para acceder a una capa inferior del signo, después alcanzar otra capa inferior y así, sucesivamente, hasta perforar el núcleo, la napa acuosa, y que el contenido brote a presión, directo hacia la superficie, como un flujo bombeado por su propia intención o voluntad o deseo de emerger. Y cuidado, que aquí nadie habla de “significados”: las metáforas y las alegorías son mentiras, siempre. Solamente los milagros son verdades. ¿Pero cuál es la forma de una palabra? ¿Dónde está su superficie, su contorno, la línea que la despega del fondo? Lo geométrico está en movimiento, orbita en espirales alrededor del número  pi.  

¿Qué tipo de volumen y cuánto ocupa la palabra “industrial”? Parece voluminosa. Denota un volumen de audio muy fuerte. ¿Por dónde se podrá abrir esa palabra? ¿Un portón grande de hierro, pintado con antióxido? ¿Qué tendrá en el interior más profundo? Un ruido puro, como de máquinas. Pero para que pueda existir ruido, siempre debería presentarse  alguna clase de acción. Y el texto no realiza acciones de ninguna clase, está fijo. Las palabras y las letras están eternamente quietas, las letras no se rozan entre sí, no se frotan, no se chocan, no actúan; el vacío entre ellas es como el vacío entre los cuerpos celestes, en él no puede propagarse el sonido. El texto es una industria silenciosa, que no hace nada.   

El tacto, obvio, ¿qué? ¿En correcto castellano acaso no se dice que la música “se toca”? A ver, probemos, ya que estamos, palpar la música que venimos oyendo en este texto, con cuidado de que no te apriete los dedos, que no te queme, o te corte, o se te clave en la palma de la mano, que no te ocasione una herida en la piel. Escuchar en *braille*. Luego el gusto... En fin, alguien había dicho (en un programa de radio o televisión o había salido en alguna columna de no me acuerdo qué, un diario o una revista) que todas las explicaciones se oponen a las cualidades estéticas y excluyen. ¿Listo? Para qué abundar en lo que ya se entendió. 

La composición integra perpendiculares visibles en los vértices pero abstractas e infinitas a lo largo y lo ancho de los planos y los espacios externos e internos. Todo sostenido por contrapesos, poleas y balancines a distancias variables, que le imprimen al conjunto los movimientos distintivos de un sistema estocástico. Sin embargo, no es una máquina, ni un artefacto mecánico. Más bien sería una caja de sorpresas, podría decirse eso. U otra cosa que, empujar, empuja.  
